name: instagram
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.2.1
  go_router: ^5.1.8
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.1.1
  image: ^3.2.2
  image_picker: ^0.8.6
  uuid: ^3.0.7
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
